"""Migratie

Revision ID: 57bb4a235aac
Revises: 
Create Date: 2021-04-07 09:00:34.993196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57bb4a235aac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medewerkers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medewerker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medewerker',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('naam', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('medewerkers')
    # ### end Alembic commands ###
